### ISSUE TITLE
Frame Speed

### ISSUE THREAD

**Issue by rizwankhanMiranshah** [duckyngo/Fast-Video-Frame-Extraction#2]
How to decrease that frame is less because its repeat same frame so many time

**Comment by duckyngo** [comment]
Our code is used to extract all frames in the video in a short time. Since our code extracts all frames so there are so many frames that look similar to the neighboring frames. If you want to extract some frames only, you can try `getFrameAtIndex()` from `MediaMetadataRetriever`.
